version: '3.8'

services:
  app:
    build: .
    container_name: ShorterApp
    ports:
      - "9999:9999"
    environment:
      SPRING_PROFILES_ACTIVE: postgres
      URL_POSTGRES: jdbc:postgresql://postgres:5432/urlshorter
      USERNAME_POSTGRES: postgres
      PASSWORD_POSTGRES: 1234
      JWT_SECRET: your_jwt_secret_key
      JWT_EXPIRATION: 3600000
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    container_name: ShorterPostgres
    environment:
      POSTGRES_DB: urlshorter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "1234:5432"
    networks:
          - app-network

networks:
    app-network:
      driver: bridge